version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:example@db:5432/blogdb
    depends_on:
      db:
        condition: service_healthy
    command: flask run --host=0.0.0.0 --port=5000
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5452:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blogdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
